import * as React from "react";
import { SVGProps, memo } from "react";
const SvgComponent = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlSpace="preserve"
    width={42}
    height={56}
    {...props}
  >
    <image
      width={42}
      height={56}
      href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACoAAAA4CAMAAAC8A5r5AAAABGdBTUEAALGPC/xhBQAAACBjSFJN AAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAB8lBMVEUAAABGWPZFV/VEV/VF VvVDV/VDVfhFVvVEVvZDVfZEV/VEVvZFVfVFV/VFV/VFV/dEVfdEV/ZEVfdGU/lFV/VEVvZFVvVE VvVCV/hEV/VEV/ZDWf9FV/ZFVvZDVvhBU/lEV/ZAWf8zTf9EV/ZAUP9DVvZEV/ZFV/ZEV/ZHUvVF VvZFVvZAYP9DVvdEVf9AVf9EV/U9Vf9EVvZFVvZCUvc7Tv9FVvVFVvZFVvZFV/ZEVvVFVvZFV/ZF VvZFV/ZFV/ZHVf9FV/ZEVvZAUvZGVvVEVvZDVvdDU/lBV/pEV/ZCWPZEV/ZEVvZEV/ZEV/ZEVvZE VvhCV/pEVvdEVvZCVfZEV/VGXf9EV/ZEV/dEV/VEVvVFVvVFVvdEVvVEV/ZEV/ZEVvVEVvVFV/ZE VvVEVvZEVvZEVvZEVvdEV/ZFVvZGV/lFV/VFVvdEV/ZFVfpFV/dEV/VFV/VFV/ZFVvVCVvdGWPZA Vf9FVvZEVvdDVfZEV/ZEVvVEV/VFVvZFV/ZFV/VFVfdFV/VEVvZDUf9EVvdCVfZFVvZFV/VEV/VD VfdFVvZFVvZFV/ZDVvVEVvVFVvVJW/9FVvZDV/VGVfdFVvZGVfdEVflBVfhEVvVDV/ZFVvVEV/dF VvZFVvVEVvVEVvZDWPdEV/dEVvdEVvZFV/b///99A/SWAAAApHRSTlMAHYHr7UxFuspU0ZVO1NNk HqU8KPGPaLhJmeAX33dEKzgUCnUQiNnahxmrwQhfDwyzFVajHw2F3sSq1b3ilG/0ElXkHE2+QS4v pDrc8nBs80cyZY4bTwuKYeidzFzwsK3nmtfsU+F0l/fjLJuYUjB+ztCn6j43GNtiV22AzfXIuV2f cRN/NsmcnmPAso1Q0oYOOzUhWUItJ7Ry5l6Rz7epPXt8sdiHQ1kAAAABYktHRKUuuUovAAAAB3RJ TUUH6AIFAAMLxyIaVgAAAppJREFUSMfNlfk/VUEYxl+lK1KEhIjiitxCcovI2p4IqaRNJSnalMpW 2kurivbt+UN7Zs65515cd86PvZ/PmXnnme+ZmTPvO3NE3FjUosXRS9yAnhjQlprB2DhoW2YC45db 4IoEA5gYY4Erk0xDJqdYJFYZl5lKanVaOpBhRNdkIktkLV/IXhjKzlmnqvWJquQycsNjed58tb4N BYW2sBEoCktGZSBgXp9WNtHdHIYszkfQSrRUSm9LGDSLetlWKff4t9Gz9nM7UBEGrQR22ONXAdXa 2wnU+OaRtRyqzva9QL12GijGh0CNu3azzKFaait76O8NrGBfkNwPHGBVBxx0tHqgSTuHgOYg2sIh Dou0ApmOVgK0aaednUccuYOtoyLHgOOO1smcsrwTyus6eSpPt04DZ0SS+EZxAK0AzlpeAtAt54A4 /R3nCbXoHfAE0AtAj+1erEyTXvZd6mPDVwNc1lNdsbv72TUQskfdKoApSmFeVolcZbPd6roGXA/d 8xs62De5f4Osb8ltlkNqFrlD724oes/ODO5FNDAsMsxGTXWrf0StbFYkB9S55TM6KGXAGJXxYGbN yadR4P4DpU/EsnhI5dGoBY49npMgT4CnelY846OPe/nzmOYXL5vm5dKkDr6n2R5JItgra3ey7XOS HAFV8eliXfhao28iDcu8L1P12yKFdkZC2xgtZ9m97yKh7zlWmuVOfWiQiDZkmDbEmCHRLtEp96h8 HP7kFv0fbHrms0uy9gvw1R36jREbcUWWGvPPsVyN9rhBv2v0h5vPJ/eTCdhhRieITs+6Fxc0/nRn hP/ydDPKKy5V/PrKMpg6BtPyi2WfCe2ybnretJMm9Ld1U3id63xh8wB/WPkK/kYZF9vYb/50kX/X ES4Uvj/GhQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyNC0wMi0wNFQyMzowMzoxMSswMTowMJVKwKsA AAAldEVYdGRhdGU6bW9kaWZ5ADIwMjQtMDItMDRUMjM6MDM6MTErMDE6MDDkF3gXAAAAAElFTkSu QmCC"
    />
  </svg>
);
const Memo = memo(SvgComponent);
export default Memo;
